feat: udistrital/planeacion_cliente/issues/972
udistrital/planeacion_seguimiento_mid pull request #2
Opened 2024-04-17 04:33 UTC by felimarod

udistrital/planeacion_cliente/issues/972

2024-04-17 20:25 UTC, a52290451 requested changes

2024-04-17 20:25 UTC, a52290451 commented on routers/commentsRouter_controllers.go
Se requiere realizar una corrección en los endpoints, reemplazando "_" por "-". @felimarod

2024-04-18 13:22 UTC, felimarod commented on routers/commentsRouter_controllers.go
El cambio es en los parametros de las rutas?
Por ejemplo, tengo la ruta "localhost:8080/v1/actividades/:plan_id/:index/:trimestre" en el swagger
Intente cambiarlo a  "localhost:8080/v1/actividades/:plan-id/:index/:trimestre" pero me daba un error, así que los puse "localhost:8080/v1/actividades/:planId/:index/:trimestre" y por el estilo, quedo a la espera para saber si es eso o no y así subir los cambios

2024-04-18 15:29 UTC, felimarod commented on routers/commentsRouter_controllers.go
Listo, ya quedó

2024-04-22 00:09 UTC, a52290451 approved these changes

2024-04-22 00:10 UTC, merged